name: syncable_entity_state_data
description: Annotation and code generator for syncable entity state data classes producing *EntityState implementations of BaseEntityState.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"

isar_version: &isar_version 3.3.0-dev.2

dependencies:
  analyzer: ^7.0.0
  build: any
  source_gen: ^3.0.0
  meta: ^1.11.0
  json_annotation: ^4.9.0
  dart_style: ^3.0.0
  sltt_core:
    path: ../sltt_core
  pub_semver: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.9
  test: ^1.25.0
  json_serializable: ^6.8.0
  build_test: any
  isar_community_generator: *isar_version
